#les regex  sont testées dans l'ordre
#un même groupe (ldap) peut matcher  plusieurs regex
#une 'regex' définit un ensemble de 'group' NC, fonction des groupes Grouper qui match.
#a chaque 'group' on peut associer:
#un 'quotaG' qui definit le quota des membres du groupe, sans quota un utilisateur ne sera pas créé (il peut l'être avec un autre groupe).
#un groupFolder 'folder' si on a un 'quotaF' le groupfolder sera créé/modifié sinon le groupe sera associé au groupfolder ssi il existe.
#permF definit les droits du groupe sur le groupefolder  

 
---
suffixGroup: ':LDAP'
etabs:
  - nom: GIP-RECIA
    siren: 18450311800020
    ldapFilterGroups: '(|(cn=coll:Collectivites:GIP-RECIA:*)(cn=coll:admin:*:GIP-RECIA:*)(cn=coll:admin:local:admin_GIP-RECIA))'
    regexes:
      - regex: '^coll:Collectivites:GIP-RECIA:PERSONNEL:GEOMATIQUE$'
        last: ifMatch
        
      - regex: '^coll:Collectivites:(GIP-RECIA):PERSONNEL:(?:Tous_)?([^:]+)$'
        groups:
          - group: 'GIP-RECIA'
            folders:
              - folder: &folderRecia 'GIP-RECIA'
                permF: []
                quotaF: 1
              - folder: 'GIP-RECIA/Commun'
                permF:
                  -  write
                  -  share
                  -  delete
                quotaF: 12
          
          - group: '%2$s.%1$s'
            quotaG: 2
            folder: '%1$s/%2$s'
            permF:
              - write
              - share
              - delete
            quotaF: 10
              
      - regex: '^coll:Collectivites:(GIP-RECIA):STAGIAIRE:(?:Tous_)?([^:]+)$'
        groups:
          - group: 'GIP-RECIA'
            folder: *folderRecia
          - group: '%2$s.%1$s'
            quotaG: 1
              
      - regex: '^coll:admin:Nextcloud:(GIP-RECIA):(?:Tous_)?([^:]+)$'
        group: '%2$s.admin.%1$s'
        admin: '%1$s/%2$s'
       
      - regex: '^coll:admin:local:admin_(GIP-RECIA)$'
        group: 'admin.%1$s'
        folder: 'GIP-RECIA'
        permF:
          - write
          - delete
        admin: '^%1$s(/.+)?'
            
    # les regles pour l'asc:
      - regex: '^coll:Collectivites:(GIP-RECIA):groupes_locaux:(ASC):([^:]+)$'
        groups:
          - group: '%2$s.%1$s'
            folder: 'ASC'
            permF: []
            quotaF: 1
          - group: '%3$s.%1$s'
            folder: 'ASC/%3$s'
            permF:
              - write
              - share
              - delete
            quotaF: 10
              
      - regex: '^coll:Collectivites:(GIP-RECIA):groupes_locaux:(ASC):(Bureau_ASC)$'
        groups:
          - group: '%3$s.%1$s'
            admin: '^ASC(/.*)$'
...
